# 아래 client-id와 client-secret은 예시로 넣은 더미데이터입니다. 참고만 부탁드려요.
spring:
  h2:
    console:
      enabled: true
      path: /console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 958180173202-sii4epowero1eouvvjrlrnt27sikub08k.apps.googleusercontent.com
            client-secret: k0asdfag801WdcJF8k9ST_8SG9
          facebook:
            client-id: 11612612521462
            client-secret: 6578235217c5c365a98c51b02d0308ac
custom:
  oauth2:
    kakao:
      client-id: 949a30f13ff0dfa5e0e55dc9ec8ef679
      client-secret: C0R3TPtITHU0fglTtDQgmIL3qnuCZygx
    naver:
      client-id: B5yvH3Zaweyawerawwe6repj4z0L
      client-secret: sArXFasdfawef
